### ISSUE TITLE
Add Suspicion Agent

### ISSUE THREAD

**Issue by CR-Gjx** [lafmdp/Awesome-Papers-Autonomous-Agent#1]
Hi,

Thanks for your contribution to the research community. Can you check if the paper below matches your interest? Thank you very much!

[Suspicion Agent: Playing Imperfect Information Games with Theory of Mind Aware GPT-4](http://arxiv.org/abs/2309.17277)

[Project Demo](https://huggingface.co/spaces/cr7-gjx/Suspicion-Agent-Demo)  
[Game Data Replay](https://huggingface.co/spaces/cr7-gjx/Suspicion-Agent-Data-Visualization)
[Code](https://github.com/CR-Gjx/Suspicion-Agent)

**Comment by lafmdp** [comment]
Thanks for your reminding. I have carefully checked this paper and found that this paper falls under the category of LLM-based agent for specific tasks. The paper collection has been updated accordingly.
